FROM ubuntu_miniconda
MAINTAINER Jorge Alarcon Ochoa


RUN apt-get update -y && apt-get install -y xvfb firefox                        
RUN cd /bin && \                                                                
    curl -L https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz | tar xz && \
    chmod +x geckodriver                                                        
RUN echo "export PATH=$PATH:$(pwd)/bin/geckodriver" >> ~/.bashrc                
ENV PATH $PATH:$(pwd)/bin/geckodriver


RUN curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list && \
    apt-get update -y && apt-get install -y google-chrome-stable
RUN curl -LO http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip && chmod +x chromedriver
RUN mv -f chromedriver /usr/local/share/chromedriver && \
    ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver && \
    ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
