FROM ubuntu:16.04
MAINTAINER Jorge Alarcon Ochoa


RUN apt-get update && apt-get install -y curl unzip  

RUN apt-get update && apt-get install -y python3-dev python3-setuptools build-essential libssl-dev libffi-dev    

RUN curl -LO https://repo.continuum.io/archive/Anaconda3-4.3.0-Linux-x86_64.sh && \
    bash Anaconda3-4.3.0-Linux-x86_64.sh -p /Anaconda -b && \                   
    rm Anaconda3-4.3.0-Linux-x86_64.sh && \                                     
    rm -rf /var/lib/apt/lists/*
ENV PATH $PATH:/Anaconda/bin 
RUN conda update -y conda
RUN pip install --upgrade pip      
